name: Publish packages to NPM

on:
  push:
    tags:
      - '**'
    branches:
      - main
      - beta
      - alpha

jobs:
  test:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        node:
          - '16.x'
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js ${{matrix.node}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          cache: 'npm'
      - name: Installing
        run: npm ci
      - name: Testing packages
        run: npm test

  publish-providers:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node:
          - '16.x'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - name: Building
        run: npm run build
      - name: Publishing with Node.js ${{matrix.node}}
        run: ./scripts/publish providers
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

  publish-cli:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node:
          - '16.x'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - name: Building
        run: npm run build
      - name: Publishing with Node.js ${{matrix.node}}
        run: ./scripts/publish cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
